### ISSUE TITLE
Unable to lock car, 'NoneType' object has no attribute 'completed'

### ISSUE THREAD

**Issue by zachberger** [dahlb/ha_kia_hyundai#111]
**Region and Brand of car**
2024 NA Kia Niro EV 

**Describe the bug**
Unable to lock car, "Failed to call service lock/lock. 'NoneType' object has no attribute 'completed'"

**Debug logs if an error occurred**
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 107, in _async_lock
    await entity.async_lock(**_add_default_code(entity, service_call))
  File "/config/custom_components/ha_kia_hyundai/lock.py", line 47, in async_lock
    await self.hass.async_create_task(
  File "/config/custom_components/ha_kia_hyundai/vehicle.py", line 33, in mark_used_wrapper
    await func(*args, **kwargs)
  File "/config/custom_components/ha_kia_hyundai/vehicle.py", line 218, in lock_action
    await self.api_cloud.lock(vehicle=self, action=action)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_us_kia.py", line 33, in request_with_active_session_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_kia_hyundai/api_cloud_us_kia.py", line 324, in lock
    await self._lock(vehicle)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_us_kia.py", line 64, in current_action_wrapper
    if not self._current_action.completed():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'completed'
```

**To Reproduce**
1. Go to default dashboard
2. Click on lock 
![Screenshot 2023-12-17 at 5 17 15 PM](https://github.com/dahlb/ha_kia_hyundai/assets/1634878/d243fb2c-1784-4447-9319-55877e0c35f6)

**Expected behavior**
Car locks

**Screenshots**
![Screenshot 2023-12-17 at 5 17 15 PM](https://github.com/dahlb/ha_kia_hyundai/assets/1634878/8af18ddb-bca6-4999-a219-b245bf7f09c1)
![Screenshot 2023-12-17 at 5 18 18 PM](https://github.com/dahlb/ha_kia_hyundai/assets/1634878/9c9b8a2f-06e5-4083-bd5c-d4802fedfd91)

**Additional context**

**Comment by dahlb** [comment]
thanks so much for writing this up, I missed a typo introduced in #103's quick fix; this is fixed in https://github.com/dahlb/ha_kia_hyundai/commit/0508c38c6bd689f33bdf9d653722da8184b836a1 release 1.8.6

**Comment by zachberger** [comment]
Thanks! I can confirm it’s fixed after upgrading.
